# Generated by Django 5.0.4 on 2024-04-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefas',
            new_name='Tarefa',
        ),
    ]
